### ISSUE TITLE
NPE in OutputFragment android.bluetooth.BluetoothHidDevice.getConnectionState

### ISSUE THREAD

**Issue by stud0709** [stud0709/OneMoreSecret#11]
OneMoreSecret version: alpha-0.17

----- STACK TRACE -----
java.lang.NullPointerException: Attempt to invoke virtual method 'int
android.bluetooth.BluetoothHidDevice.getConnectionState(android.bluetooth.BluetoothDevice)'
on a null object reference
at
com.onemoresecret.OutputFragment.checkConnectSelectedDevice(OutputFragment.java:282)
at
com.onemoresecret.OutputFragment.-$$Nest$mcheckConnectSelectedDevice(Unknown
Source:0)
at
com.onemoresecret.OutputFragment$1.onItemSelected(OutputFragment.java:180)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
at
android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown
Source:0)
at
android.widget.AdapterView$SelectionNotifier.run[https://selectionnotifier.run/](AdapterView.java:910)

at
android.os.Handler.handleCallback(Handler.java[Handler.java:942]:942[Handler.java:942])
at
android.os.Handler.dispatchMessage(Handler.java[Handler.java:99]:99[Handler.java:99])
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at
[android.app](http://android.app/)[https://android.app/].ActivityThread.main(ActivityThread.java:7940)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android[https://com.android/].internal.os.RuntimeInit$MethodAndArgsCaller.run[https://methodandargscaller.run/](RuntimeInit.java:548)
at
com.android[https://com.android/].internal.os.ExecInit.main(ExecInit.java:49)
at
com.android[https://com.android/].internal.os.RuntimeInit.nativeFinishInit(Native
Method)
at
com.android[https://com.android/].internal.os.RuntimeInit.main(RuntimeInit.java:355)

----- DEVICE -----
Brand: google
Device: raven
Model: Pixel 6 Pro
ID: TQ3A.230805.001
Product: raven

----- ANDROID OS -----
Android SDK: 33
Android release: 13
Android incremental: 2023080800
----- END OF REPORT -----

**Comment by stud0709** [comment]
presumably fixed as of alpha-0.18
